### ISSUE TITLE
fix downstream build issue following #50 change (external fmt)

### ISSUE THREAD

**Issue by cav71** [conda-forge/spdlog-feedstock#52]
### Solution to issue cannot be found in the documentation.

- [X] I checked the documentation.

### Issue

Hi, 
#50 seems breaking building mamba (and probably other spdlog downstream packages).

To build the libmamba, I've followed the instructions in [build steps](https://mamba.readthedocs.io/en/latest/developer_zone/build_locally.html)
```
.../include/spdlog/fmt/fmt.h:24:14: fatal error: 'spdlog/fmt/bundled/core.h' file not found
```

### Installed packages

```shell
# packages in environment at /Users/antonio/envs/mamba-libmamba:
#
# Name                    Version                   Build  Channel
bzip2                     1.0.8                h3422bc3_4    conda-forge
c-ares                    1.18.1               h3422bc3_0    conda-forge
c-compiler                1.5.1                h5008568_0    conda-forge
ca-certificates           2022.9.24            h4653dfc_0    conda-forge
cctools                   973.0.1             hcbb26d4_10    conda-forge
cctools_osx-arm64         973.0.1             he930820_10    conda-forge
clang                     14.0.4               hce30654_0    conda-forge
clang-14                  14.0.4          default_h81a5282_0    conda-forge
clang_osx-arm64           14.0.4               hc634a12_2    conda-forge
clangxx                   14.0.4          default_hb7ecf47_0    conda-forge
clangxx_osx-arm64         14.0.4               hb7a33d8_2    conda-forge
cli11                     2.3.0                hb7217d7_0    conda-forge
cmake                     3.23.1               he7c8c24_0    conda-forge
compiler-rt               14.0.4               h4418234_0    conda-forge
compiler-rt_osx-arm64     14.0.4               hb07f8d1_0    conda-forge
cpp-expected              1.0.0                h3e96240_0    conda-forge
cxx-compiler              1.5.1                hffc8910_0    conda-forge
expat                     2.4.9                hb7217d7_0    conda-forge
fmt                       9.1.0                hffc8910_0    conda-forge
gmock                     1.11.0               h3e96240_0    conda-forge
gtest                     1.11.0               h3e96240_0    conda-forge
icu                       70.1                 h6b3803e_0    conda-forge
krb5                      1.19.3               he492e65_0    conda-forge
ld64                      609                 h619f069_10    conda-forge
ld64_osx-arm64            609                 h132958c_10    conda-forge
libarchive                3.5.2                hdd7f49f_3    conda-forge
libclang-cpp14            14.0.4          default_h81a5282_0    conda-forge
libcurl                   7.82.0               h9476f53_0    conda-forge
libcxx                    14.0.6               h2692d47_0    conda-forge
libedit                   3.1.20191231         hc8eb9b7_2    conda-forge
libev                     4.33                 h642e427_1    conda-forge
libiconv                  1.17                 he4db4b2_0    conda-forge
libllvm14                 14.0.4               h37c5ba8_0    conda-forge
libnghttp2                1.47.0               h519802c_1    conda-forge
libsodium                 1.0.18               h27ca646_1    conda-forge
libsolv                   0.7.22               h1280f1d_0    conda-forge
libssh2                   1.10.0               h7a5bd25_3    conda-forge
libuv                     1.44.2               he4db4b2_0    conda-forge
libxml2                   2.10.3               h87b0503_0    conda-forge
libzlib                   1.2.13               h03a7124_4    conda-forge
llvm-openmp               14.0.4               hd125106_0    conda-forge
llvm-tools                14.0.4               h37c5ba8_0    conda-forge
lz4-c                     1.9.3                hbdafb3b_1    conda-forge
lzo                       2.10              h642e427_1000    conda-forge
ncurses                   6.3                  h07bb92c_1    conda-forge
ninja                     1.11.0               hf86a087_0    conda-forge
nlohmann_json             3.11.2               h2e04ded_0    conda-forge
openssl                   3.0.5                h03a7124_2    conda-forge
reproc                    14.2.3               h3422bc3_0    conda-forge
reproc-cpp                14.2.3               hbdafb3b_0    conda-forge
rhash                     1.4.3                he4db4b2_0    conda-forge
sigtool                   0.1.3                h44b9a77_0    conda-forge
spdlog                    1.10.0                        2    file:///Users/antonio/repos/conda
tapi                      1100.0.11            he4954df_0    conda-forge
termcolor-cpp             2.0.0                hc021e02_0    conda-forge
xz                        5.2.6                h57fd34a_0    conda-forge
yaml-cpp                  0.7.0                hb7217d7_2    conda-forge
zlib                      1.2.13               h03a7124_4    conda-forge
zstd                      1.5.2                h8128057_4    conda-forge
```

### Environment info

```shell
active environment : mamba-libmamba
    active env location : /Users/antonio/envs/mamba-libmamba
            shell level : 1
       user config file : /Users/antonio/.condarc
 populated config files : /Users/antonio/envs/mambaforge/.condarc
          conda version : 4.14.0
    conda-build version : 3.22.0
         python version : 3.10.6.final.0
       virtual packages : __osx=12.6=0
                          __unix=0=0
                          __archspec=1=arm64
       base environment : /Users/antonio/envs/mambaforge  (writable)
      conda av data dir : /Users/antonio/envs/mambaforge/etc/conda
  conda av metadata url : None
           channel URLs : https://conda.anaconda.org/conda-forge/osx-arm64
                          https://conda.anaconda.org/conda-forge/noarch
                          file:///Users/antonio/repos/conda/osx-arm64
                          file:///Users/antonio/repos/conda/noarch
          package cache : /Users/antonio/envs/pkgs
       envs directories : /Users/antonio/envs
                          /Users/antonio/envs/mambaforge/envs
                          /Users/antonio/.conda/envs
               platform : osx-arm64
             user-agent : conda/4.14.0 requests/2.28.1 CPython/3.10.6 Darwin/21.6.0 OSX/12.6
                UID:GID : 502:20
             netrc file : None
           offline mode : False
```

**Comment by beenje** [comment]
[libhdbpp-timescale](https://github.com/conda-forge/libhdbpp-timescale-feedstock) built fine in staged-recipes with spdlog 1.10 build 0, but failed after merge with 1.10 build 1 (full [log](https://dev.azure.com/conda-forge/84710dde-1620-425b-80d0-4cf5baca359d/_apis/build/builds/593854/logs/7)):

```
2022-10-22T14:55:30.0511953Z /home/conda/feedstock_root/build_artifacts/libhdbpp-timescale_1666450389850/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_pl/include/fmt/core.h:1757:7: error: static assertion failed: Cannot format an argument. To make type T formattable provide a formatter<T> specialization: https://fmt.dev/latest/api.html#udt
```

This isn't the same error message as mentioned here but I guess the origin is the same?

**Comment by bluescarni** [comment]
@beenje spdlog is now using the latest fmt version, 9.x, which changed some functionality in a manner which is not backwards compatible with earlier fmt versions. See:

https://github.com/fmtlib/fmt/releases/tag/9.0.0

If I had to take a wild guess, I'd say that the removal of the ostream formatter is what broke libhdbpp.

**Comment by beenje** [comment]
> @beenje spdlog is now using the latest fmt version, 9.x, which changed some functionality in a manner which is not backwards compatible with earlier fmt versions. See:
> 
> https://github.com/fmtlib/fmt/releases/tag/9.0.0
> 
> If I had to take a wild guess, I'd say that the removal of the ostream formatter is what broke libhdbpp.

Thanks! I'll report that upstream.

**Comment by jjerphan** [comment]
I believe this issue has been fixed thanks to https://github.com/mamba-org/mamba/pull/2048.
